import { spawnSync } from 'node:child_process';
import { copyFileSync, renameSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { chromium } from 'playwright';
import { expect, it } from 'vitest';
import { startServer } from '../../server/main.ts';
import { copyFixture } from '../helpers/project.ts';
import { invariants as libraryChecks } from '../../web/src/review/_internal/MediaLibrary.verify.ts';
import { invariants as previewChecks } from '../../web/src/review/_internal/MediaPreview.verify.ts';
import { revealReelRail } from '../helpers/review-rail.ts';

it('keeps every media path in one rail list, previews in the frame, reuses duplicate content and drops sound onto an owner', { timeout: 90_000 }, async () => {
  const dir = copyFixture('footage-project');
  const generated = spawnSync('ffmpeg', ['-v', 'error', '-y', '-f', 'lavfi', '-i', 'sine=frequency=440:duration=2', join(dir, 'tone.wav')], { encoding: 'utf8' });
  expect(generated.status, generated.stderr).toBe(0);
  copyFileSync(join(dir, 'tone.wav'), join(dir, 'duplicate.wav'));
  for (const [file, options] of [['poster.png', ['-frames:v', '1']], ['film.mp4', ['-c:v', 'libx264']]] as const) {
    const picture = spawnSync('ffmpeg', ['-v', 'error', '-y', '-f', 'lavfi', '-i', 'color=c=lime:s=160x90:r=30:d=2', ...options, join(dir, file)], { encoding: 'utf8' });
    expect(picture.status, picture.stderr).toBe(0);
  }
  const reel = join(dir, 'reels/founder-talk');
  const plan = { duration: 4, clips: [], media: { schema: 1, tracks: [{ id: 'music', name: 'Music', order: 0, gain: 1, mute: false }], sources: [], placements: [{ id: 'gap', role: 'gap', duration: 4 }], sequence: ['gap'] } };
  writeFileSync(join(reel, 'plan.json'), JSON.stringify(plan));
  writeFileSync(join(reel, 'v1/plan.json'), JSON.stringify(plan));
  const server = await startServer({ projectDir: dir, port: 0 });
  const original = await server.project.referenceMedia('tone.wav');
  const browser = await chromium.launch();
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    await page.goto(server.url);
    await page.getByRole('navigation', { name: 'Reels' }).getByRole('button', { name: 'Founder talk: going local-first' }).click();
    await page.getByRole('button', { name: 'Review', exact: true }).click();
    await page.getByRole('tab', { name: 'Media rail', exact: true }).click();
    const library = page.getByRole('region', { name: 'Project media library' });
    await library.locator('[data-media-path="duplicate.wav"]').waitFor();
    expect(await library.locator('[data-media-path="tone.wav"]').count()).toBe(1);
    expect(await library.getByRole('heading', { name: 'In this project' }).count()).toBe(0);
    expect((await server.project.listMedia()).length).toBe(1);
    await library.getByRole('button', { name: 'Preview duplicate.wav', exact: true }).click();
    const preview = page.locator('.rv-frame [data-verify-unit="MediaPreview"]');
    await preview.waitFor();
    await expect.poll(() => preview.getByLabel('Preview of duplicate.wav').evaluate((element: HTMLAudioElement) => element.readyState)).toBeGreaterThan(0);
    expect(await library.getByRole('button', { name: 'Preview duplicate.wav', exact: true }).getAttribute('aria-pressed')).toBe('true');
    expect((await server.project.listMedia()).length).toBe(1);
    expect(await library.locator('[data-media-path="duplicate.wav"]').count()).toBe(1);
    const previewVerdicts = await preview.evaluate((root, checks) => checks.map((check) => Boolean((0, eval)(`(${check})`)(root))), previewChecks.map((rule) => rule.check.toString()));
    expect(previewVerdicts).toEqual(previewChecks.map(() => true));
    const invalidPreview = await preview.evaluate((root, checks) => { const copy = root.cloneNode(true) as Element; copy.setAttribute('data-verify-kind', 'unknown'); return checks.map((check) => Boolean((0, eval)(`(${check})`)(copy))); }, previewChecks.map((rule) => rule.check.toString()));
    expect(invalidPreview.filter((pass) => !pass)).toHaveLength(1);
    await page.getByRole('button', { name: 'Close media preview' }).click();
    await page.getByLabel('Playhead', { exact: true }).fill('1');
    await library.getByRole('button', { name: 'Add duplicate.wav at playhead' }).click();
    const last = async () => (await server.project.readEditList('founder-talk')).operations.at(-1)!;
    await expect.poll(last).toMatchObject({ kind: 'placement-add', placement: { source: original.id, role: 'audio', at: 1, fadeIn: 0.2, fadeOut: 0.2 } });
    const track = page.locator('[data-track="music"] .native-lane-bars');
    await library.locator('[data-media-path="duplicate.wav"]').dragTo(track);
    await expect.poll(last).toMatchObject({ kind: 'placement-add', placement: { source: original.id, role: 'audio', track: 'music', at: 2 } });
    await library.getByRole('tab', { name: 'Audio', exact: true }).click();
    await library.getByLabel('Search media').fill('duplicate');
    expect(await library.locator('[data-media-path]').count()).toBe(1);
    const verdicts = await library.evaluate((root, checks) => checks.map((check) => Boolean((0, eval)(`(${check})`)(root))), libraryChecks.map((rule) => rule.check.toString()));
    expect(verdicts).toEqual(libraryChecks.map(() => true));
    const invalidCount = await library.evaluate((root, checks) => { const copy = root.cloneNode(true) as Element; copy.setAttribute('data-verify-count', '99'); return checks.map((check) => Boolean((0, eval)(`(${check})`)(copy))); }, libraryChecks.map((rule) => rule.check.toString()));
    expect(invalidCount.filter((pass) => !pass)).toHaveLength(1);
    await library.getByLabel('Search media').fill('');
    await library.getByRole('tab', { name: 'All', exact: true }).click();
    await library.getByRole('button', { name: 'Preview poster.png', exact: true }).click();
    await expect.poll(() => preview.getByAltText('Preview of poster.png').evaluate((element: HTMLImageElement) => element.naturalWidth)).toBe(160);
    await page.getByRole('button', { name: 'Close media preview' }).click();
    let failPreview = true;
    await page.route((url) => /^\/media\/[^/]+$/.test(url.pathname), (route) => failPreview ? route.fulfill({ status: 503, body: 'Preview unavailable' }) : route.continue());
    await library.getByRole('button', { name: 'Preview film.mp4', exact: true }).click();
    await preview.getByRole('button', { name: 'Retry preview' }).waitFor();
    const failedChecks = await preview.evaluate((root, checks) => checks.map((check) => Boolean((0, eval)(`(${check})`)(root))), previewChecks.map((rule) => rule.check.toString()));
    expect(failedChecks).toEqual(previewChecks.map(() => true));
    failPreview = false;
    await preview.getByRole('button', { name: 'Retry preview' }).click();
    await expect.poll(() => preview.getByRole('alert').count()).toBe(0);
    await expect.poll(() => preview.getByLabel('Preview of film.mp4').evaluate((element: HTMLVideoElement) => element.readyState)).toBeGreaterThan(0);
    await page.getByRole('button', { name: 'Close media preview' }).click();
    await library.locator('[data-media-path="film.mp4"]').dragTo(page.locator('[data-role="main"] .native-lane-bars'));
    const film = (await server.project.listMedia()).find((entry) => entry.path === 'film.mp4')!;
    await expect.poll(last).toMatchObject({ kind: 'placement-add', index: 1, placement: { source: film.id, role: 'main', in: 0, out: 2 } });
    const operations = (await server.project.readEditList('founder-talk')).operations;
    expect(operations.at(-2)).toMatchObject({ kind: 'placement-split', placement: 'gap', at: 2 });
    // Close the player requests before simulating an externally moved file on Windows.
    await page.goto('about:blank');
    await expect.poll(() => { try { renameSync(join(dir, 'tone.wav'), join(dir, 'moved.wav')); return true; } catch (error) { if ((error as NodeJS.ErrnoException).code === 'EBUSY') return false; throw error; } }, { timeout: 5_000 }).toBe(true);
    await page.goto(server.url);
    await revealReelRail(page);
    await page.getByRole('navigation', { name: 'Reels' }).getByRole('button', { name: 'Founder talk: going local-first' }).click();
    await page.getByRole('button', { name: 'Review', exact: true }).click();
    await page.getByRole('tab', { name: 'Media rail', exact: true }).click();
    const missing = library.locator('[data-media-path="tone.wav"]');
    await missing.getByText('File missing', { exact: true }).waitFor();
    await missing.getByLabel('Relink tone.wav').selectOption('moved.wav');
    await missing.getByRole('button', { name: 'Relink', exact: true }).click();
    await expect.poll(async () => (await server.project.listMedia()).find((entry) => entry.id === original.id)?.path).toBe('moved.wav');
    await expect.poll(() => library.getByText('File missing', { exact: true }).count()).toBe(0);
    expect(await library.getByRole('button', { name: 'Retry', exact: true }).count()).toBe(0);
  } finally { await browser.close(); await server.close(); }
});
