import { spawnSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { chromium } from 'playwright';
import { expect, it } from 'vitest';
import { startServer } from '../../server/main.ts';
import { copyFixture } from '../helpers/project.ts';
import { invariants } from '../../web/src/review/_internal/EditorialLanes.verify.ts';

it('edits and retimes native words in lanes, pins their saved occurrences, retypes captions and repairs an interrupted graphic', { timeout: 90_000 }, async () => {
  const dir = copyFixture('footage-project');
  const generated = spawnSync('ffmpeg', ['-v', 'error', '-y', '-f', 'lavfi', '-i', 'color=c=lime:s=160x90:r=30:d=4', '-c:v', 'libx264', join(dir, 'take.mp4')], { encoding: 'utf8' });
  expect(generated.status, generated.stderr).toBe(0);
  const reel = join(dir, 'reels/founder-talk');
  const media = (prefix: string) => ({ schema: 1, sources: [{ id: 'take', name: 'Take', kind: 'video', duration: 4, audio: false, path: `${prefix}take.mp4`, words: [{ text: 'hello', start: 0.5, end: 0.9 }, { text: 'world', start: 1.2, end: 1.8 }] }], placements: [{ id: 'first', role: 'main', source: 'take', in: 0, out: 4 }], sequence: ['first'] });
  const plan = { title: 'Editorial lanes', duration: 4, captions: true, sections: [{ id: 'all', name: 'All', start: 0, end: 4 }], clips: [{ id: 'card', title: 'Card', clip: 'card.html', placement: 'first', in: 0.5, out: 1.8, kind: 'overlay' }] };
  writeFileSync(join(reel, 'plan.json'), JSON.stringify({ ...plan, media: media('../../') }));
  writeFileSync(join(reel, 'v1/plan.json'), JSON.stringify({ ...plan, media: media('../../../') }));
  const server = await startServer({ projectDir: dir, port: 0 });
  const browser = await chromium.launch();
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    await page.goto(server.url);
    await page.getByRole('navigation', { name: 'Reels' }).getByRole('button', { name: 'Founder talk: going local-first' }).click();
    await page.getByRole('button', { name: 'Review', exact: true }).click();
    const lanes = page.locator('[data-verify-unit="EditorialLanes"]');
    const last = async () => (await server.project.readEditList('founder-talk')).operations.at(-1)!;
    await page.getByRole('button', { name: 'Pin word at 0.50 in first' }).click();
    await page.getByLabel('Pin comment', { exact: true }).fill('Saved hello');
    await page.getByRole('button', { name: 'Save pin', exact: true }).click();
    await expect.poll(() => server.project.listComments('founder-talk', 1)).toMatchObject([{ text: 'Saved hello', pin: { placement: 'first', sourceTime: 0.5 } }]);
    await lanes.getByRole('button', { name: '1. Saved hello' }).click();
    expect(await page.getByLabel('Playhead', { exact: true }).inputValue()).toBe('0.50');
    await lanes.getByRole('button', { name: 'Edit word hello at 0.50 in first' }).click();
    await page.getByLabel('Word at 0.50 in first', { exact: true }).fill('hi');
    await page.getByLabel('Word at 0.50 in first', { exact: true }).press('Enter');
    await expect.poll(last).toMatchObject({ kind: 'word-text', placement: 'first', at: 0.5, text: 'hi' });
    await lanes.scrollIntoViewIfNeeded();
    const edge = lanes.getByLabel('Word start at 0.50 in first', { exact: true });
    const box = (await edge.boundingBox())!;
    const width = (await lanes.locator('.native-lane').nth(2).locator('.native-lane-bars').boundingBox())!.width;
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
    await page.mouse.down();
    await page.mouse.move(box.x + box.width / 2 + width / 40, box.y + box.height / 2, { steps: 8 });
    await page.mouse.up();
    await expect.poll(async () => { const op = await last(); return op.kind === 'word-timing' ? op.start : null; }).toBeCloseTo(0.6, 2);
    await expect.poll(() => lanes.getByRole('button', { name: /^Edit word hi at 0.60/ }).count()).toBe(1);
    await lanes.locator('.native-lane').nth(1).getByRole('button').first().click();
    await page.getByLabel('Caption at 0.60').fill('fresh words');
    await page.getByLabel('Caption at 0.60').press('Enter');
    await expect.poll(last).toMatchObject({ kind: 'phrase-text', placement: 'first', text: 'fresh words' });
    const graphic = lanes.locator('[data-graphic="card"]');
    await graphic.click();
    expect(await graphic.getAttribute('aria-pressed')).toBe('true');
    await graphic.press('Enter');
    const inspector = page.getByRole('region', { name: 'Graphics attachments' });
    await inspector.getByLabel('Graphic scale card').fill('1.2');
    await inspector.getByLabel('Graphic scale card').press('Tab');
    await expect.poll(last).toMatchObject({ kind: 'element-offset', clip: 'card', element: '@clip', scale: 1.2 });
    const snipped = await page.request.post(`${server.url}/api/reels/founder-talk/edits`, { data: { kind: 'placement-snip', from: 1, to: 3 } });
    expect(snipped.status()).toBe(201);
    await page.reload();
    await lanes.locator('[data-graphic="card"][data-verify-broken-graphic="true"]').waitFor();
    await lanes.locator('[data-graphic="card"]').dblclick();
    await inspector.getByRole('button', { name: 'Trim to source 0.50–1.00s' }).click();
    await expect.poll(() => lanes.locator('[data-verify-broken-graphic="true"]').count()).toBe(0);
    const verdicts = await lanes.evaluate((root, checks) => checks.map((check) => Boolean((0, eval)(`(${check})`)(root))), invariants.map((rule) => rule.check.toString()));
    expect(verdicts).toEqual(invariants.map(() => true));
    const invalidCount = await lanes.evaluate((root, checks) => { const copy = root.cloneNode(true) as Element; copy.setAttribute('data-verify-words', '99'); return checks.map((check) => Boolean((0, eval)(`(${check})`)(copy))); }, invariants.map((rule) => rule.check.toString()));
    expect(invalidCount.filter((pass) => !pass)).toHaveLength(1);
  } finally { await browser.close(); await server.close(); }
});

